### ISSUE TITLE
Request Flash Pro Extension Support

### ISSUE THREAD

**Issue by asaia** [davidderaedt/CC-Extension-Builder-for-Brackets#10]
Requesting to add a drop down list to support Flash Pro extensions... I noticed this line was commented out in main.js under Hosts. 
//< Host Name="FLPR" Version="[13.1,14.0]" />

Took me a while to figure out what Flash Pro's Host name should be but once I found this line adding it manually is a simple work around.

**Comment by davidderaedt** [comment]
Fixed in 0.7.5
