### ISSUE TITLE
Can't run extension

### ISSUE THREAD

**Issue by ahuet** [davidderaedt/CC-Extension-Builder-for-Brackets#11]
Simply by clicking on File > New Creative Cloud Extension, then click on the create extension button, the window closes and nothing happens.

A capture of the Chrome console:
![capture](https://cloud.githubusercontent.com/assets/7301062/2705923/af53103a-c486-11e3-9f17-2ab4ba66f0f5.png)

My config:
Win 7 Family Premium SP1 (x64)
Adobe InDesign CC 9.2.1 x64
Brackets Sprint 38 (0.38.0-12606 release 4df8afdad)

When can we expect a fix ?

Thanks for the job.

**Comment by davidderaedt** [comment]
Hi

Can you please check if the manifest file mentioned on the third error was indeed created or not?

Thanks

David Deraedt - Creative Cloud Consultant, Adobe +33 6 72 74 00 75

On 15 Apr 2014, at 12:17 , ahuet <notifications@github.com<mailto:notifications@github.com>> wrote:

Simply by clicking on File > New Creative Cloud Extension, then click on the create extension button, the window closes and nothing happens.

A capture of the Chrome console:
[capture]https://cloud.githubusercontent.com/assets/7301062/2705923/af53103a-c486-11e3-9f17-2ab4ba66f0f5.png

My config:
Win 7 Family Premium SP1 (x64)
Adobe InDesign CC 9.2.1 x64
Brackets Sprint 38 (0.38.0-12606 release 4df8afdad)

When can we expect a fix ?

Thanks for the job.

**Comment by ahuet** [comment]
Yes, both directories (com.example.helloworld and CSXS) and manifest.xml file exist.

**Comment by davidderaedt** [comment]
Ok thanks, so it looks like the extension was indeed created.
So, if the manifest file contains strings like {extid}, you'll have to replace them by hand.
If not (and you find, say "com.example.helloworld" as the extension ID), the extension is already valid, only the project's folder was not automatically open in brackets, for some reason, but you can open it in brackets by yourself.

David Deraedt - Creative Cloud Consultant, Adobe +33 6 72 74 00 75

On 15 Apr 2014, at 13:59 , Alex <notifications@github.com<mailto:notifications@github.com>> wrote:

Yes, both directories (com.example.helloworld and CSXS) and manifest.xml file exist.

**Comment by ahuet** [comment]
Yes the manifest file contains {extid}...

In fact, it seems that the path must not contain any "\" char. So I replace it with a regex:
Changes I made into main.js file of the plugin line 95:
var manifestFile =  new NativeFileSystem.FileEntry(path + "/CSXS/manifest.xml");
by:
var manifestFile = new NativeFileSystem.FileEntry(path.replace(/\/g,"/") + "/CSXS/manifest.xml");

and now the manisfest file is ok. But it always break in Brackets for some other reason... I'm taking a look and I post here as soons as I found something.

**Comment by ahuet** [comment]
Well, good news !

In the same function createExtension(data), I missed also to replace at line 99 and 101 the path var.

The complete replacement:

function createExtension(data) {

```
    var moduleFolder = FileUtils.getNativeModuleDirectoryPath(module);
    var templateFolder = new NativeFileSystem.DirectoryEntry(moduleFolder + TEMPLATE_FOLDER_NAME);

    var copyPromise = nodeConnection.domains.ccext.copyTemplate(templateFolder.fullPath, data.extid);

    copyPromise.fail(function (err) {
        console.error("[brackets-ccext-node] failed to run ccext.copyTemplate", err);
    });

    copyPromise.done(function (path) {

        // Modify manifest file             
        var manifestFile = new NativeFileSystem.FileEntry(path.replace(/\\/g,"/") + "/CSXS/manifest.xml");
        processTemplateFile(manifestFile, data);

        // Open project and document
        ProjectManager.openProject(path.replace(/\\/g,"/")).done(
            function () {
                DocumentManager.getDocumentForPath(path.replace(/\\/g,"/") + "/index.html").done(
                    function (doc) {
                        DocumentManager.setCurrentDocument(doc);
                        alert(SUCCESS_MSG);
                    }
                );
            }
        );

    });
}
```

I think it's a M$ Windows issue with system path separator...

Now all is working as expected :)

Thank you for your good job !

**Comment by davidderaedt** [comment]
Thanks a lot for your help. I just pushed a fix to normalize windows paths returned from node. 
Please reinstall from this repository, and it should now work as expected.
