### ISSUE TITLE
Doesn't work with Edge Code preview 0.98.0-359086273

### ISSUE THREAD

**Issue by avaneste** [davidderaedt/CC-Extension-Builder-for-Brackets#12]
CC-Extension works with Brackets (Sprint 40 / 0.40.0-13109) but fails with Edge Code CC Preview (version expérimentale 0.98.0-359086273 (Preview) (On branch master,master 41761a1cf))

**Comment by avaneste** [comment]
Actually, extension is marked as Installed in Edge Code but when trying to launch from Edge Code, index.html is not created.

**Comment by davidderaedt** [comment]
Edge code is not supported anymore, please use brackets instead

**Comment by avaneste** [comment]
Ok David, I'll do. Thanks !
