### ISSUE TITLE
cc2014 compatibility

### ISSUE THREAD

**Issue by studioxop** [davidderaedt/CC-Extension-Builder-for-Brackets#13]
is there a cc2014 version available?
This version of the extension is not compatible with the new cc2014

**Comment by davidderaedt** [comment]
Working on it as we speak

**Comment by niittymaa** [comment]
This is more than superb after got this work with CC2014 indeed!

**Comment by ghost** [comment]
Is 2014 compatibility still a work in progress? I just started using this so maybe I'm missing something, but it doesn't seem like it's there yet so I thought I'd ask.

**Comment by davidderaedt** [comment]
Fixed since CC SDK merge
