### ISSUE TITLE
Doesn't work with Brackets 1.4

### ISSUE THREAD

**Issue by Chris2011** [davidderaedt/CC-Extension-Builder-for-Brackets#24]
I installed it via this tutorial: http://davidderaedt.github.io/CC-Extension-Builder-for-Brackets/ and after this I created a new plugin but not with file > New CC Extension, because there is no option. The option is now a new menu called CC Extension Build > New CC Extension. After this, a new app was created and I saw the alert that everything was created. When I open PS and go to extension, there is only a Adobe Color Theme. Not more.

Regards

Chris

**Comment by Chris2011** [comment]
Ok sry I will close this, I forgot to build it to an zxp file: I didn' read the tutorial to the end ^^.

**Comment by xberg** [comment]
Chris,
I am having the exact same problem. What do you mean that you need to create a ZXP file? In the video:
https://www.youtube.com/watch?v=LX-WtRdZ2H4
we do not see him creating such a file. Can you detail how you solved this to help me please?
thanks.

**Comment by Chris2011** [comment]
You don't need the zxp file, you can copy the folder to C:\Users\UserName\AppData\Roaming\Adobe\CEP\extensions.

This is what brackets create:
C:\Users\UserName\AppData\Roaming\Adobe\CEP\extensions\com.example.helloworld'

I removed the apostroph first, I didn't notice that. The problem is this:

``` HTML
   <Host Name="PHXS" Version="[15.0,15.9]" />
   <Host Name="PHSP" Version="[15.0,15.9]" />
```

change it to

``` HTML
   <Host Name="PHXS" Version="15.0" />
   <Host Name="PHSP" Version="15.0" />
```

after this, it works. But if you call it inside photoshop, it says, that the plugin couldn't load properly, because it was not signed correctly. Thats because you need zxp for this. Hope that helps.

Cheers

Chris

**Comment by xberg** [comment]
Thank you so much Chris, this helped a lot. 
1. Removing the apostrophe
2. changing the version number.

I now _see_ the panel indicated under Windows > Extension but can still not open it (not signed correctly). I used ZXPSignCmd.exe to create a .ZXP file but am not sure how to install. I tried using the Adobe Extension Manager CC but this program does not even show Photoshop CC 2015...

**Comment by Chris2011** [comment]
I didn't get it to work too with the ZXP. I had the .zxp package and I installed it via the extension manager, I didn't know that it has to show the photoshop, maybe this is the problem yes.
