### ISSUE TITLE
InDesign CC Extension

### ISSUE THREAD

**Issue by ff6347** [davidderaedt/CC-Extension-Builder-for-Brackets#5]
The eclipse plugin seems to be able to build ID extensions. When is ID support coming to brackets?

**Comment by davidderaedt** [comment]
InDesign CC does not support HTML panels for now, hence supporting it here would not make much sense. I will add support for inDesign the day it does support HTML panels.

**Comment by ff6347** [comment]
Doesn't it? On the adobe labs page for extension builder 3 preview InDesign is listed.

```
What Adobe Products support HTML Extensions?
```

Adobe Photoshop CC, Premiere Pro CC, Prelude CC, Illustrator CC, InDesign CC and Flash Professional CC support modern HTML extensions as of July 31, 2013.

http://labs.adobe.com/technologies/extensionbuilder3/

:fab

Am 11.08.2013 um 15:59 schrieb David Deraedt notifications@github.com:

**Comment by ff6347** [comment]
Hi David,
looks like it should work in the upcoming version of ID. I created a simple "Hello World" with the Eclipse plugin but the Extension Manager says: "Can't install this Extension. InDesign Version 9.1 or higher needed"
my ID is still 9.0.
Cheers
:F

**Comment by ponychicken** [comment]
ID 9.1 is out now & I'm able to build and run HTML extensions in ID

**Comment by davidderaedt** [comment]
Just added support for InDesign
