### ISSUE TITLE
Hi david, how can i create a panel menu?

### ISSUE THREAD

**Issue by RayPS** [davidderaedt/CC-Extension-Builder-for-Brackets#6]

**Comment by davidderaedt** [comment]
What do you mean by menu precisely?

**Comment by RayPS** [comment]
![menu](https://f.cloud.github.com/assets/1941540/1080138/82fe4d44-155c-11e3-9434-db2754c93986.png)

for example this is DevRocket's panel menu.

**Comment by davidderaedt** [comment]
Sorry, this issue is related to CEP4 (Adobe's CEF based engine for HTML panels), but unrelated to this project.
